spring.datasource.url=${MYSQL_DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:finance_tracker}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${MYSQL_DB_USERNAME:${DB_USERNAME:root}}
spring.datasource.password=${MYSQL_DB_PASSWORD:${DB_PASSWORD:root}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8