spring.application.name=finance
spring.datasource.url=${MYSQL_DB_URL:jdbc:mysql://localhost:3306/finance_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=n3u3da!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=validate

yahoo.finance.base-url=${YAHOO_FINANCE_BASE_URL:https://query2.finance.yahoo.com}
yahoo.finance.quote-path=${YAHOO_FINANCE_QUOTE_PATH:/v8/finance/chart}
yahoo.finance.region=${YAHOO_FINANCE_REGION:US}
yahoo.finance.user-agent=${YAHOO_FINANCE_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36}

finance.holding-last-price-refresh.interval-ms=${HOLDING_LAST_PRICE_REFRESH_INTERVAL_MS:60000}
finance.holding-last-price-refresh.initial-delay-ms=${HOLDING_LAST_PRICE_REFRESH_INITIAL_DELAY_MS:60000}
